[package]
name = "rust_design_pattern_derivative_pricing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"
rand = "0.8.5"
num-traits = "0.2.15"
superslice = "1.0.0"
rayon = "1.7.0"
actix-web = "4.3.1"

env_logger = "0.10.0"
futures-util = { version = "0.3.28", default-features = false, features = ["std"] }
json = "0.12.4"
log = "0.4.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
approx = "0.5.1"
