[package]
name = "rust_design_pattern_derivative_pricing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"
rand = "0.8.5"
num-traits = "0.2.14"
superslice = "1.0.0"
rayon = "1.5.1"